apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - datastore.yaml
  
helmCharts:
- name: kubecodex
  repo: https://thecodingsheikh.github.io/helm-charts
  releaseName: kubecodex
  version: 1.2.0
  valuesFile: values.yaml