apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: slurm

resources:
  - slurm-ssd-conf.yaml
  
helmCharts:
- name: slurm
  repo: oci://ghcr.io/slinkyproject/charts
  version: 1.0.0
  releaseName: slurm
  includeCRDs: true
  namespace: slurm
  valuesFile: values.yaml