apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kro
  repo: oci://registry.k8s.io/kro/charts
  version: 0.8.4
  includeCRDs: true
  namespace: kro
  releaseName: kro