apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: liqo
  repo: https://helm.liqo.io
  version: v1.0.1
  includeCRDs: true
  namespace: liqo
  releaseName: liqo
  valuesFile: values.yaml

patchesStrategicMerge:
  - patch-crd.yaml