annotations:
  lab.backstage.io/add-to-catalog: "true"
  lab.backstage.io/owner: abso
  lab.backstage.io/system-type: app
  lab.backstage.io/system: app
  backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=backstage'
  lab.backstage.io/component-type: service
  lab.backstage.io/lifecycle: managed
  lab.backstage.io/links: string
  lab.backstage.io/title: My App
  lab.backstage.io/name: my-app