homepage:
  config:
    bookmarks:
    services:
    widgets:
      - greeting:
          text_size: xl
          text: Home Lab
      - kubernetes:
          cluster:
            cpu: true
            label: cluster
            memory: true
            show: true
            showLabel: true
          nodes:
            cpu: true
            memory: true
            show: false
            showLabel: true
    kubernetes:
      mode: cluster
    settings:
      cardBlur: sm
      hideVersion: true
      disableCollapse: false

  serviceAccount:
    create: true
    name: homepage
  enableRbac: true

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: lab-issuer
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Homepage"
        gethomepage.dev/icon: "homepage.png"
      hosts:
        - host: home.lab.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - home.lab.com
          secretName: home-tls