apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - https://github.com/cozystack/cozystack/releases/download/v0.37.2/cozystack-installer.yaml

patches:
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: KUBERNETES_SERVICE_HOST
          value: kubernetes.default.svc.cluster.local
      - op: replace
        path: "/spec/template/spec/containers/0/env/1"
        value:
          name: KUBERNETES_SERVICE_PORT
          value: "443"
    target:
      kind: Deployment
      name: cozystack