apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operators

helmCharts:
- name: mariadb-operator-crds
  repo: https://helm.mariadb.com/mariadb-operator
  version: 25.10.3
  releaseName: mariadb-operator-crds
  includeCRDs: true
  namespace: operators

- name: mariadb-operator
  repo: https://helm.mariadb.com/mariadb-operator
  version: 25.10.3
  releaseName: mariadb-operator
  includeCRDs: true
  namespace: operators

