apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: flux2
  repo: https://fluxcd-community.github.io/helm-charts
  version: 2.15.0
  releaseName: flux2
  includeCRDs: true
  namespace: flux
  valuesFile: values.yaml