apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wggatewayclients.networking.liqo.io
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wggatewayservers.networking.liqo.io
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shadowpods.offloading.liqo.io
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualnodes.offloading.liqo.io
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true