apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: managed-services-releases
  namespace: argo-cd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - git:
        files:
          - path: "releases/*/*/manifest.yaml"
          - path: "releases/*/*/*/*.yaml"
        repoURL: https://github.com/TheCodingSheikh/managed-services.git
        revision: HEAD
        values:
          tenant_name: '{{ index (splitList "/" .path.path) 1 }}'
          folder: '{{ index (splitList "/" .path.path) 2 }}'
          clean_filename: '{{ trimSuffix ".yaml" .path.basename }}'
          parent_dir: '{{ index (splitList "/" .path.path) (sub (len (splitList "/" .path.path)) 2) }}'
  template:
    metadata:
      name: placeholder
      namespace: argo-cd
    spec:
      project: "managed-services"
      source:
        path: '{{ .path.pathDir }}'
        repoURL: 'https://github.com/TheCodingSheikh/managed-services.git'
        targetRevision: HEAD
      destination:
        name: in-cluster
        namespace: placeholder
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        managedNamespaceMetadata:
          labels:
            capsule.clastix.io/tenant: "{{ .values.folder }}"
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    metadata:
      name: {{ if ne .values.folder .values.parent_dir -}}
        {{ .values.folder }}-{{ .values.tenant_name }}-{{ .values.clean_filename }}-{{ .values.parent_dir }}
      {{- else if ne .values.clean_filename "manifest" -}}
        {{ .values.folder }}-{{ .values.tenant_name }}-{{ .values.clean_filename }}
      {{- else -}}
        {{ .values.folder }}-{{ .values.tenant_name }}
      {{- end }}
    spec:
      destination:
        namespace: {{ if ne .values.folder .values.parent_dir -}}
          {{ .values.folder }}-{{ .values.tenant_name }}-{{ .values.clean_filename }}-{{ .values.parent_dir }}
        {{- else -}}
          {{ .values.folder }}-{{ .values.tenant_name }}
        {{- end }}