apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: managed-services-releases
  namespace: argo-cd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - git:
        files:
          - path: "releases/**/manifest.yaml"
        repoURL: https://github.com/TheCodingSheikh/managed-services.git
        revision: HEAD
        requeueAfterSeconds: 20
        values:
          tenant: "{{index .path.segments 2}}"
          name: "{{.path.basename}}"
  template:
    metadata:
      name: placeholder
      namespace: argo-cd
    spec:
      project: "managed-services"
      source:
        path: '{{ .path.path }}'
        repoURL: 'https://github.com/TheCodingSheikh/managed-services.git'
        targetRevision: HEAD
      destination:
        name: in-cluster
        namespace: placeholder
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        managedNamespaceMetadata:
          labels:
            capsule.clastix.io/tenant: "{{ .values.tenant }}"
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- $segments := splitList "/" .path.path -}}
    {{- $service := index $segments 3 -}}
    metadata:
      name: '{{ .values.tenant }}-tenant-{{ .values.name }}'
      namespace: argo-cd
      annotations:
        {{ if gt (len .path.segments) 3 }}
        service: "{{ $service }}"
        {{ end }}
    spec:
      destination:
        namespace: '{{ .values.tenant }}-tenant-{{ .values.name }}'
        name: in-cluster