apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: managed-services-releases
  namespace: argo-cd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - git:
        directories:
          - path: releases/*/*
          - path: releases/*/*/*
        repoURL: https://github.com/TheCodingSheikh/managed-services.git
        revision: HEAD
        values:
          tenant: '{{ index (splitList "/" .path.path) 1 }}'
          parent: '{{ index (splitList "/" .path.path) 2 }}'
          service: '{{ if eq (len (splitList "/" .path.path)) 4 }}{{ index (splitList "/" .path.path) 3 }}{{ else }}base{{ end }}'
          cluster: "in-cluster"
  template:
    metadata:
      name: '{{ .values.tenant }}-{{ .values.parent }}-{{ .values.service }}'
      namespace: argo-cd
    spec:
      project: "managed-services"
      source:
        path: '{{ .path.path }}'
        repoURL: 'https://github.com/TheCodingSheikh/managed-services.git'
        targetRevision: HEAD
      destination:
        name: '{{ .values.cluster }}'
        namespace: '{{ .values.tenant }}-{{ .values.parent }}-{{ .values.service }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- if eq .values.service "base" }}
    metadata:
      name: "{{ .values.tenant }}-{{ .values.parent }}"
      namespace: argo-cd
    spec:
      destination:
        name: '{{ .values.cluster }}'
        namespace: null
      syncPolicy:
        syncOptions: []
    {{- end }}