apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: managed-services-releases
  namespace: argo-cd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - git:
        files:
          - path: "releases/*/*/manifest.yaml" 
          - path: "releases/*/*/*/*.yaml"
        repoURL: https://github.com/TheCodingSheikh/managed-services.git
        revision: HEAD
        values:
          tenant_name: '{{ index (splitList "/" .path.path) 1 }}'
          folder: '{{ index (splitList "/" .path.path) 2 }}'
          depth: '{{ len (splitList "/" .path.path) }}'
          filename: '{{ .path.filenameNormalized }}'
          service_name: '{{ if eq (len (splitList "/" .path.path)) 5 }}{{ index (splitList "/" .path.path) 3 }}{{ else }}none{{ end }}'
  template:
    metadata:
      name: placeholder
      namespace: argo-cd
    spec:
      project: "managed-services"
      source:
        path: '{{ .path.pathDir }}'
        repoURL: 'https://github.com/TheCodingSheikh/managed-services.git'
        targetRevision: HEAD
      destination:
        name: in-cluster
        namespace: placeholder
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        managedNamespaceMetadata:
          labels:
            capsule.clastix.io/tenant: "{{ .values.folder }}"
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    metadata:
      name: {{ if eq .values.depth "5" }}
        {{- .values.folder }}-{{ .values.tenant_name }}-{{ .values.filename }}-{{ .values.service_name }}
      {{- else }}
        {{- .values.folder }}-{{ .values.tenant_name }}
      {{- end }}
    spec:
      destination:
        namespace: {{ if eq .values.depth "5" }}
          {{- .values.folder }}-{{ .values.tenant_name }}-{{ .values.filename }}-{{ .values.service_name }}
        {{- else }}
          {{- .values.folder }}-{{ .values.tenant_name }}
        {{- end }}