apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hyperdx-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: hyperdx-secret
  data:
  - secretKey: HYPERDX_API_KEY
    remoteRef:
      property: ingestion-api-key
      key: monitoring/clickstack/hyperdx