apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: keycloak-pushsecret
spec:
  deletionPolicy: None
  updatePolicy: IfNotExists
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: global-password-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          property: password
          remoteKey: data/platform/keycloak/users/admin