apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: litellm-helm
  repo: oci://docker.litellm.ai/berriai
  version: 0.1.832
  valuesFile: values.yaml
  releaseName: litellm
  namespace: litellm

# patches:
#   - target:
#       kind: Deployment
#       name: litellm
#     patch: |-
#       - op: replace
#         path: /spec/template/spec/volumes/0
#         value:
#           name: litellm-config
#           configMap:
#             name: litellm-config