apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: vcluster
  repo: https://charts.loft.sh
  version: 0.24.1
  valuesFile: values.yaml
  releaseName: kubeflow
  namespace: vcluster-kubeflow