apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - chart
  - rate-limit-patch.yaml


# configMapGenerator:
# - name: litellm-config
#   behavior: merge
#   files:
#     - custom_sso.py