apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kubeflow
  repo: https://thecodingsheikh.github.io/helm-charts
  version: 1.1.0
  valuesFile: values.yaml
  releaseName: kubeflow
